name: fluid_dialog
description: A dialog that  can switch between multiple contents and animates size and alignment dynamically.
version: 2.0.0
repository: https://github.com/RoundedInfinity/fluid_dialog

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

screenshots:
  - description: "A cover image of the plugin"
    path: images/cover.png
  - description: "A GIF that showcases the use of fluid dialog"
    path: images/video.gif
topics:
  - dialog
  - animation
  - widgets
